/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    models: Model;
    types: Type;
    categories: Category;
    products: Product;
    variants: Variant;
    customers: Customer;
    media: Media;
    'global-medias': GlobalMedia;
    'contact-requests': ContactRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    types: TypesSelect<false> | TypesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'global-medias': GlobalMediasSelect<false> | GlobalMediasSelect<true>;
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
    Home: Home;
    WarrantyServices: WarrantyService;
    AboutUs: AboutUs;
    TermsConditions: TermsCondition;
    PrivacyPolicy: PrivacyPolicy;
    ContactUs: ContactUs;
    'cms-blog': CmsBlog;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    Home: HomeSelect<false> | HomeSelect<true>;
    WarrantyServices: WarrantyServicesSelect<false> | WarrantyServicesSelect<true>;
    AboutUs: AboutUsSelect<false> | AboutUsSelect<true>;
    TermsConditions: TermsConditionsSelect<false> | TermsConditionsSelect<true>;
    PrivacyPolicy: PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    ContactUs: ContactUsSelect<false> | ContactUsSelect<true>;
    'cms-blog': CmsBlogSelect<false> | CmsBlogSelect<true>;
  };
  locale: null;
  user:
    | (Admin & {
        collection: 'admins';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: string;
  modelName: string;
  modelCode: string;
  type: string | Type;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types".
 */
export interface Type {
  id: string;
  typeName: string;
  typeCode: string;
  category?: (string | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  categoryName: string;
  categoryCode: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  productName: string;
  productCode: string;
  price: number;
  stock: number;
  status: 'active' | 'inactive';
  model: string | Model;
  variant: (string | Variant)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  variantName: string;
  variantCode: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  product?: (string | null) | Product;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-medias".
 */
export interface GlobalMedia {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: string;
  fullName: string;
  email: string;
  company: string;
  jobTitle: string;
  interestedProducts: (string | Category)[];
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'models';
        value: string | Model;
      } | null)
    | ({
        relationTo: 'types';
        value: string | Type;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'global-medias';
        value: string | GlobalMedia;
      } | null)
    | ({
        relationTo: 'contact-requests';
        value: string | ContactRequest;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  modelName?: T;
  modelCode?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types_select".
 */
export interface TypesSelect<T extends boolean = true> {
  typeName?: T;
  typeCode?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  categoryName?: T;
  categoryCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productName?: T;
  productCode?: T;
  price?: T;
  stock?: T;
  status?: T;
  model?: T;
  variant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  variantName?: T;
  variantCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-medias_select".
 */
export interface GlobalMediasSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  company?: T;
  jobTitle?: T;
  interestedProducts?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | GlobalMedia;
  contactInfo?: {
    title?: string | null;
    socialLinks?:
      | {
          platform?: ('facebook' | 'line' | 'youtube' | 'instagram' | 'phone' | 'tiktok' | 'twitter') | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  menuColumns?:
    | {
        title: string;
        items?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomSection?: {
    copyright?: string | null;
    links?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Home".
 */
export interface Home {
  id: string;
  slides?:
    | {
        backgroundImage: string | GlobalMedia;
        heading: string;
        description?: string | null;
        ctaButton?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Time between slide transitions
   */
  autoPlaySpeed?: number | null;
  'product-showcase': {
    heading: string;
    description: string;
    products?:
      | {
          image: string | GlobalMedia;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  sections?:
    | {
        layout: 'horizontal-text-left' | 'horizontal-text-right';
        heading: string;
        description: string;
        image: string | GlobalMedia;
        ctaButton?: {
          enabledButton?: boolean | null;
          text?: string | null;
          link?: string | null;
        };
        styling?: {
          textAreaBg?: ('white' | 'light-beige' | 'light-gray' | 'light-blue') | null;
        };
        id?: string | null;
      }[]
    | null;
  'business-overview': {
    heading: string;
    image: string | GlobalMedia;
    button?: {
      text?: string | null;
      url?: string | null;
    };
  };
  'product-overview': {
    heading: string;
    image: string | GlobalMedia;
    features?:
      | {
          icon: string | GlobalMedia;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  'brand-intro': {
    image: string | GlobalMedia;
    text: string;
    button: {
      label: string;
      url: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WarrantyServices".
 */
export interface WarrantyService {
  id: string;
  banner: {
    backgroundImage: string | GlobalMedia;
    heading: string;
  };
  header: string;
  'types-of-warranty': {
    heading: string;
    description: string;
    warranties?:
      | {
          logo: string | GlobalMedia;
          title: string;
          detail: string;
          id?: string | null;
        }[]
      | null;
  };
  'contact-hatari-suport': {
    heading?: string | null;
    button: {
      text: string;
      url: string;
    };
    backgroudImage: string | GlobalMedia;
  };
  'service-center': {
    header: string;
    detail: string;
    locations: {
      'main-location': {
        'center-name': string;
        contact: {
          location: string;
          'operating-hours': string;
          'telephone-number': string;
        };
        button: {
          text: string;
          url: string;
        };
      };
      'secondary-location'?:
        | {
            'center-name': string;
            contact: {
              location: string;
              'operating-hours': string;
              'telephone-number': string;
              button: {
                text: string;
                url: string;
              };
            };
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUs".
 */
export interface AboutUs {
  id: string;
  banner: {
    backgroundImage: string | GlobalMedia;
    heading: string;
  };
  heading: string;
  ourHistory?:
    | {
        historyImage: string | GlobalMedia;
        herder: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  'company-overview': {
    heading: string;
    'sub-heading': string;
    companies?:
      | {
          image: string | Media;
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    'our-story': {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    'ender-image': string | GlobalMedia;
  };
  'brand-vision': {
    backgroudImage: string | GlobalMedia;
    heading: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  'tagline-banner': {
    tagline: string;
    backgroundImage: string | GlobalMedia;
  };
  'our-values': {
    heading: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    'values-card'?:
      | {
          image: string | GlobalMedia;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsConditions".
 */
export interface TermsCondition {
  id: string;
  'terms-and-conditions': {
    title: string;
    introduction: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrivacyPolicy".
 */
export interface PrivacyPolicy {
  id: string;
  'privacy-policy': {
    title: string;
    introduction: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    'background-image': string | GlobalMedia;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-blog".
 */
export interface CmsBlog {
  id: string;
  /**
   * Select a blog post to feature at the top
   */
  blog: string | Blog;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  contactInfo?:
    | T
    | {
        title?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  menuColumns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  bottomSection?:
    | T
    | {
        copyright?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        backgroundImage?: T;
        heading?: T;
        description?: T;
        ctaButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        id?: T;
      };
  autoPlaySpeed?: T;
  'product-showcase'?:
    | T
    | {
        heading?: T;
        description?: T;
        products?:
          | T
          | {
              image?: T;
              title?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        layout?: T;
        heading?: T;
        description?: T;
        image?: T;
        ctaButton?:
          | T
          | {
              enabledButton?: T;
              text?: T;
              link?: T;
            };
        styling?:
          | T
          | {
              textAreaBg?: T;
            };
        id?: T;
      };
  'business-overview'?:
    | T
    | {
        heading?: T;
        image?: T;
        button?:
          | T
          | {
              text?: T;
              url?: T;
            };
      };
  'product-overview'?:
    | T
    | {
        heading?: T;
        image?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  'brand-intro'?:
    | T
    | {
        image?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WarrantyServices_select".
 */
export interface WarrantyServicesSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        backgroundImage?: T;
        heading?: T;
      };
  header?: T;
  'types-of-warranty'?:
    | T
    | {
        heading?: T;
        description?: T;
        warranties?:
          | T
          | {
              logo?: T;
              title?: T;
              detail?: T;
              id?: T;
            };
      };
  'contact-hatari-suport'?:
    | T
    | {
        heading?: T;
        button?:
          | T
          | {
              text?: T;
              url?: T;
            };
        backgroudImage?: T;
      };
  'service-center'?:
    | T
    | {
        header?: T;
        detail?: T;
        locations?:
          | T
          | {
              'main-location'?:
                | T
                | {
                    'center-name'?: T;
                    contact?:
                      | T
                      | {
                          location?: T;
                          'operating-hours'?: T;
                          'telephone-number'?: T;
                        };
                    button?:
                      | T
                      | {
                          text?: T;
                          url?: T;
                        };
                  };
              'secondary-location'?:
                | T
                | {
                    'center-name'?: T;
                    contact?:
                      | T
                      | {
                          location?: T;
                          'operating-hours'?: T;
                          'telephone-number'?: T;
                          button?:
                            | T
                            | {
                                text?: T;
                                url?: T;
                              };
                        };
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUs_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        backgroundImage?: T;
        heading?: T;
      };
  heading?: T;
  ourHistory?:
    | T
    | {
        historyImage?: T;
        herder?: T;
        description?: T;
        id?: T;
      };
  'company-overview'?:
    | T
    | {
        heading?: T;
        'sub-heading'?: T;
        companies?:
          | T
          | {
              image?: T;
              name?: T;
              description?: T;
              id?: T;
            };
        'our-story'?: T;
        'ender-image'?: T;
      };
  'brand-vision'?:
    | T
    | {
        backgroudImage?: T;
        heading?: T;
        description?: T;
      };
  'tagline-banner'?:
    | T
    | {
        tagline?: T;
        backgroundImage?: T;
      };
  'our-values'?:
    | T
    | {
        heading?: T;
        description?: T;
        'values-card'?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsConditions_select".
 */
export interface TermsConditionsSelect<T extends boolean = true> {
  'terms-and-conditions'?:
    | T
    | {
        title?: T;
        introduction?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrivacyPolicy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  'privacy-policy'?:
    | T
    | {
        title?: T;
        introduction?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-blog_select".
 */
export interface CmsBlogSelect<T extends boolean = true> {
  blog?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}